version: '3.8'

services:
  frontend:
    image: lakpahana/teamwallet-app-pipeline-client:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: lakpahana/teamwallet-app-pipeline-back:latest
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
