version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: .
    ports:
      - "3002:3032"
    environment:
      - NODE_ENV=production
